### ISSUE TITLE
 ‘utils.dino_utils’ has no attribute ‘DINOHead’ 

### ISSUE THREAD

**Issue by zmxkzserz65** [Naeem-Paeedeh/ADAPTER#1]
Thank you for your excellent research!
When we run your code, 240 of configs\configs_training.py reports an error: attributeError: module ‘utils.dino_utils’ has no attribute ‘DINOHead’ 
And we didn't find any declaration or definition of DINOHead class in utils\dino_utils.
We are looking forward to your reply.

**Comment by Naeem-Paeedeh** [comment]
Hello,

I appreciate your interest in our work and informing me about this issue.

DINOHead is defined in the [ViT_CCT.py](https://github.com/Naeem-Paeedeh/ADAPTER/blob/main/models/ViT_CCT.py) file. Importing the DINOHead directly from [ViT_CCT.py](https://github.com/Naeem-Paeedeh/ADAPTER/blob/main/models/ViT_CCT.py) (line 7) should resolve the issue for the version of Python you are using.

I may have moved it to the model's definitions during the refactoring and reorganization of the code to make it simpler and easier to read. [dino_utils](https://github.com/Naeem-Paeedeh/ADAPTER/blob/main/utils/dino_utils.py) is imported into the [configs_training.py](https://github.com/Naeem-Paeedeh/ADAPTER/blob/main/configs/configs_training.py) file, and DINOHead and the other definitions in the ViT_CCT are imported into the dino_utils (line 15). Therefore, the program should also have access to the definition of DINOHead via dino_utils.

**Comment by zmxkzserz65** [comment]
Thanks for your response, the issue has been resolved
