### ISSUE TITLE
Request open source pre-trained weights 

### ISSUE THREAD

**Issue by MengqingSun** [Naeem-Paeedeh/ADAPTER#2]
Hello, this is a really valuable article. I am very interested in this work. I would be grateful if you could provide the pre-trained weights of Mini-ImageNet → BSCD-FSL and Tiered-ImageNet → BSCD-FSL.

**Comment by Naeem-Paeedeh** [comment]
Hello,

I appreciate your interest.

The pre-trained weights are now available for download.

**Comment by MengqingSun** [comment]
Thank you very much for your reply, it is very helpful for my research.
